title: Projects
description: A compilation of my personal projects
baseurl: "/projects" # the subpath of your site, e.g. /blog
url: "https://vengaza.github.io" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: just-the-docs/just-the-docs
search_enabled: true
search.heading_level: 3

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Aux links for the upper right navigation
aux_links:
  "Back to portfolio":
    - "https://vengaza.github.io/"

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: 
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

### Footer content ###

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2017-2022 Dustin Jones."

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false